//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryAutomationSystem.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblKullaniciKitap
    {
        public int ID { get; set; }
        public Nullable<int> KullaniciID { get; set; }
        public Nullable<int> KitapID { get; set; }
        public Nullable<System.DateTime> OduncAlmaTarihi { get; set; }
        public Nullable<System.DateTime> OduncVermeTarihi { get; set; }
        public Nullable<bool> Durum { get; set; }
    
        public virtual TblKitaplar TblKitaplar { get; set; }
        public virtual TblKullanici TblKullanici { get; set; }
    }
}
