//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryAutomationSystem.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblKitaplar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblKitaplar()
        {
            this.TblKullaniciKitap = new HashSet<TblKullaniciKitap>();
            this.TblStok = new HashSet<TblStok>();
        }
    
        public int KitapID { get; set; }
        public string KitapAd { get; set; }
        public string Yazar { get; set; }
        public string Yayinevi { get; set; }
        public string ISBN { get; set; }
        public Nullable<int> SayfaSayisi { get; set; }
        public Nullable<int> Kategori { get; set; }
    
        public virtual TblKategoriler TblKategoriler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblKullaniciKitap> TblKullaniciKitap { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblStok> TblStok { get; set; }
    }
}
